#!/bin/bash

node -v
npm -v
yarn -v

## Theia
git clone https://github.com/raspberrypi/tools
cd tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian
yarn install
export CC=/opt/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc
export CXX=/opt/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++
npm rebuild --target_arch=arm
unset CC CXX
